config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user/menus#welcome'
  
  mount ActionCable.server, at: '/cable'
  get :chatroom, to: "chatrooms#index"
  post :message, to: "messages#create"
  
  scope module: :user do
    resource :profile, except: [:destroy]
    get :mainmenu, to: "menus#mainmenu"
    scope module: :details do
      get :majors
      get :schools
      get :grades
      get :verification
    end
  end
  
  scope module: :auth do
    delete :logout, to: 'sessions#destroy'
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
  end
  
  scope module: :menu do
    resources :eduvideos, :problemsets, :consultations, param: :subject  do
      member do
        resource :chapter, path: '/:chapter' do
          member do
            resource :title, path: '/:title'
          end
        end
      end
    end
    
    resource :tryouts, only: :show  do
      member do
        resource :type, path: '/:type'
      end
    end
    
    resources :lessonoutlines, :path => 'outline', param: :subject do
      member do
        resource :chapter, path: '/:chapter' do
          member do
            resource :title, path: '/:title'
          end
        end
      end
    end
  end
  
  scope module: :helper do
    scope module: :utilities do
      get :name
      get :sms_verification, to:  "utilities#sms_send"
      post :sms_verification, to: "utilities#sms_generate"
    end
  end
  
  
  

  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :quizzes
end

app/models/city.rb
class City < ApplicationRecord
  has_many :schools
  belongs_to :province
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :students
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  belongs_to :grade
  has_many :lesson_items
  has_many :quizzes
end

app/models/lesson_item.rb
class LessonItem < ApplicationRecord
  belongs_to :lesson  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  def self.sendmessage(msg,user)
    ActionCable.server.broadcast 'chatroom_channel', 
    message: msg.body,
    user: user.username
  end
  
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :transaction_histories  
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :quiz
end

app/models/promo_code.rb
class PromoCode < ApplicationRecord
  has_many :user_promo_codes  
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :cities
  has_many :students
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :lesson
  belongs_to :category
  
  has_many :user_quizzes
  has_many:problems
  
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
  validates_uniqueness_of :roleName
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :city
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  
  has_one :user_student
  has_one :user, through: :user_student
  belongs_to :school
  belongs_to :university
  belongs_to :province
  belongs_to :major_interest
  belongs_to :grade
  
  validates :dob, :school, :province, :university, :major_interest, :grade, presence: true

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :user_teacher
  has_one :user, through: :user_teacher
end

app/models/university.rb
class University < ApplicationRecord
  has_many :students
  has_many :major_interests
end

app/models/user.rb
class User < ApplicationRecord
  
  belongs_to :role
  
  has_many :user_lesson
  has_many :lessons, through: :user_lesson
  has_many :user_quizzes
  has_many :quizzes, through: :user_quiz
  has_many :user_transactions
  has_many :transactions, through: :user_transaction
  has_many :user_promo_codes
  has_many :promo_codes, through: :user_promo_code
  has_many :messages
  
  has_one :user_verified
  has_one :user_student
  has_one :student, through: :user_student
  has_one :user_teacher
  has_one :teacher, through: :user_teacher
  
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9_]+\z/
  VALID_EMAIL_REGEX = /\A([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})\z/i
  VALID_FULLNAME_REGEX = /\A[a-zA-Z ]+\z/
  VALID_PHONENO_REGEX = /\A08[0-9]{9,11}\b\z/
  
  has_secure_password
  
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 5, maximum: 15 },
                       format: { with: VALID_USERNAME_REGEX }
                      
  validates :email,    presence: true, 
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 10 },
                       format: { with: VALID_EMAIL_REGEX }
                       
  validates :password_digest,    
                       presence: true,
                       length: { minimum: 6 },
                       on: [:create, :save]
                       
  validates :fullname, presence: true,
                       length: { minimum: 5 },
                       format: { with: VALID_FULLNAME_REGEX }
                       
  validates :phoneNo,  presence: true,
                       uniqueness: true,
                       length: { minimum: 5 },
                       format: { with: VALID_PHONENO_REGEX }  
                       
end

app/models/user_quiz.rb
class UserQuiz < ApplicationRecord
  belongs_to :user
  has_many :quizzes
end

app/helpers/user_helper.rb
module UserHelper
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_log_in
    if !logged_in?
      flash[:error] = "You must be logged in to do that"
      redirect_to login_path
    end
  end
  
  def student_detail
    if student_detailed?
      @student_detail = UserStudent.find(current_user.id)
    end
  end
  
  def new_user?
    !student_detailed? && !student_verified?
  end
  
  def student_detailed?
    current_user.student != nil
  end
  
  def student_verified?
    current_user.user_verified != nil
  end
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectE" %></title>
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <%= render partial: "shared/navigation" %>
  <div class="container">
    <div class="row">
      <div class="col">
        <%= render "layouts/messages" %>
        <%= yield %>
      </div>
    </div><!--/row-->
    <footer>
      <%= link_to "Mainmenu", mainmenu_path if logged_in?%></br>
      <p>&copy; Arzeeeeee 2018</p>
    </footer>
  </div> <!-- /container -->
  <%= yield :js %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<div class="ui inverted menu">
  <% if logged_in? && !new_user?%>
      <%= link_to "Mainmenu", mainmenu_path, class: "ui active item" %>
      <%= link_to current_user.username, profile_path, class: "ui item" %>
      <%= link_to "Balance: #{student_detail.balance}", profile_path, class: "ui item" %>
      <%= link_to "Point: #{student_detail.point}", profile_path, class: "ui item" %>
    <div class="right menu">
      <%= link_to "logout", logout_path, method: :delete, class: "ui item" %>
    </div>
  <% else %>
    <div class="right menu">
      <div class="item">
        <%= link_to "login", login_path, class: "ui item" %>
      </div>
      <div class="item">
        <%= link_to "signup", sign_up_path, class: "ui primary button" %>
      </div>
    </div>  
  <% end %>
</div>